### ISSUE TITLE
Difference of FORInstance dataset contents in this paper, and further releases

### ISSUE THREAD

**Issue by kasparas-k** [prs-eth/PanopticSegForLargeScalePointCloud#11]
First of all, thank you for the great work, providing the much needed instance segmentation data for ALS forest point clouds.

In the separate release of the dataset in https://doi.org/10.5281/zenodo.8287792 `NIBIO2` region is excluded, although test/dev split metadata is provided inside `data_split_metadata.csv`.

May I ask what's the reason for excluding this data? `NIBIO2` includes a lot of training data which could benefit the model. I downloaded both the laz (DOI above) and the ply (link from this repository's readme) datasets for my research, but started with the laz files due to better compatibility with the tools I use.

**Comment by bxiang233** [comment]
> First of all, thank you for the great work, providing the much needed instance segmentation data for ALS forest point clouds.
> 
> In the separate release of the dataset in https://doi.org/10.5281/zenodo.8287792 `NIBIO2` region is excluded, although test/dev split metadata is provided inside `data_split_metadata.csv`.
> 
> May I ask what's the reason for excluding this data? `NIBIO2` includes a lot of training data which could benefit the model. I downloaded both the laz (DOI above) and the ply (link from this repository's readme) datasets for my research, but started with the laz files due to better compatibility with the tools I use.

Hello,

Thank you for your interest in our work.

Regarding your question about the exclusion of the NIBIO2 region data, this was primarily due to some labeling errors in the dataset. If you look at the discussion section (Section 4.2: Dominant vs. understory trees) of our most recent paper (https://www.sciencedirect.com/science/article/pii/S0034425724000890), you will find that there are some confusions in identifying low vegetation and some understory trees within the NIBIO2. These issues have led to worse quantitative results in NIBIO2, although visually, the network’s predictions for some understory trees make sense. I hope this explanation clarifies our decision for excluding this data.

**Comment by kasparas-k** [comment]
Thank you so much for your quick and detailed response. I'll keep this in mind when using the dataset.
